export const businessInfo = {
  baseUrl: "https://www.wavesolution.com.au",
  brandName: "Wave Solution",
  businessName: "Wave Solution Cleaning & Pest Control",
  businessNameWithLocation: "Wave Solution Cleaning & Pest Control - Gold Coast",
  tradingName: "Wave Solution Cleaning",
  phoneDisplay: "0450 833 683",
  phoneInternationalDisplay: "+61 450 833 683",
  phoneE164: "+61450833683",
  phoneHref: "tel:+61450833683",
  email: "info@wavesolution.com.au",
  address: {
    locality: "Gold Coast",
    region: "QLD",
    postalCode: "4215",
    countryCode: "AU",
    countryName: "Australia",
    full: "Gold Coast, QLD 4215, Australia",
  },
  coordinates: {
    latitude: -28.1038271,
    longitude: 153.433927,
  },
  mapsUrl: "https://maps.app.goo.gl/gabLdzZ7v3VRzgk87",
  mapsEmbedUrl: "https://maps.google.com/maps?q=-28.1038271,153.4339270&z=16&output=embed",
  googleBusinessProfile: "https://maps.app.goo.gl/gabLdzZ7v3VRzgk87",
  socialProfiles: {
    google: "https://maps.app.goo.gl/gabLdzZ7v3VRzgk87",
    facebook: "https://www.facebook.com/wavesolutioncleaning",
    instagram: "https://www.instagram.com/wavesolutioncleaning",
  },
  sameAs: [
    "https://maps.app.goo.gl/gabLdzZ7v3VRzgk87",
    "https://www.facebook.com/wavesolutioncleaning",
    "https://www.instagram.com/wavesolutioncleaning",
  ],
  serviceAreas: [
    "Gold Coast",
    "Southport",
    "Surfers Paradise",
    "Broadbeach",
    "Robina",
    "Nerang",
    "Burleigh Heads",
    "Palm Beach",
    "Helensvale",
    "Coomera",
    "Varsity Lakes",
    "Carrara",
    "Merrimac",
    "Main Beach",
    "Benowa",
    "Highland Park",
  ],
  businessHoursDisplay: [
    "Monday - Friday: 8am - 6pm",
    "Saturday: 9am - 4pm",
    "Sunday: Closed",
  ],
  openingHoursSpecification: [
    {
      "@type": "OpeningHoursSpecification",
      dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
      opens: "08:00",
      closes: "18:00",
    },
    {
      "@type": "OpeningHoursSpecification",
      dayOfWeek: "Saturday",
      opens: "09:00",
      closes: "16:00",
    },
  ],
} as const

export const siteLinks = {
  home: "/",
  blog: "/blog",
  services: "/services",
  cleaningGoldCoast: "/cleaning-gold-coast",
  homeCleaning: "/house-cleaning-gold-coast",
  officeCleaning: "/office-cleaning-gold-coast",
  bondCleaning: "/bond-cleaning-gold-coast",
  endOfLeaseCleaning: "/end-of-lease-cleaning-gold-coast",
  moveInCleaning: "/move-in-cleaning-gold-coast",
  afterBuildersCleaning: "/after-builders-cleaning-gold-coast",
  commercialCleaning: "/commercial-cleaning-gold-coast",
  deepCleaning: "/deep-cleaning-gold-coast",
  carpetCleaning: "/carpet-cleaning-gold-coast",
  pestControl: "/pest-control-gold-coast",
  contact: "/contact",
  book: "/book",
  about: "/about",
  team: "/team",
  gallery: "/gallery",
  testimonials: "/testimonials",
  locations: "/locations",
  portal: "/login",
} as const
