export const businessInfo = {
  baseUrl: "https://www.wavesolution.com.au",
  brandName: "WaveSolution",
  businessName: "Wave Solution Cleaning",
  businessNameWithLocation: "Wave Solution Cleaning - Gold Coast",
  phoneDisplay: "0450 833 683",
  phoneInternationalDisplay: "+61 450 833 683",
  phoneE164: "+61450833683",
  phoneHref: "tel:+61450833683",
  email: "info@wavesolution.com.au",
  address: {
    locality: "Gold Coast",
    region: "QLD",
    postalCode: "4215",
    countryCode: "AU",
    countryName: "Australia",
    full: "Gold Coast, QLD 4215, Australia",
  },
  coordinates: {
    latitude: -28.1038271,
    longitude: 153.433927,
  },
  mapsUrl: "https://maps.google.com/?q=-28.1038271,153.4339270",
  mapsEmbedUrl: "https://maps.google.com/maps?q=-28.1038271,153.4339270&z=16&output=embed",
  serviceAreas: [
    "Gold Coast",
    "Southport",
    "Surfers Paradise",
    "Broadbeach",
    "Robina",
    "Nerang",
    "Burleigh Heads",
    "Palm Beach",
    "Helensvale",
    "Coomera",
  ],
  businessHoursDisplay: [
    "Monday - Friday: 8am - 6pm",
    "Saturday: 9am - 4pm",
    "Sunday: Closed",
  ],
  openingHoursSpecification: [
    {
      "@type": "OpeningHoursSpecification",
      dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
      opens: "08:00",
      closes: "18:00",
    },
    {
      "@type": "OpeningHoursSpecification",
      dayOfWeek: "Saturday",
      opens: "09:00",
      closes: "16:00",
    },
  ],
} as const

export const siteLinks = {
  home: "/",
  services: "/services",
  homeCleaning: "/services/home-cleaning",
  contact: "/contact",
  book: "/book",
  about: "/about",
  gallery: "/gallery",
  testimonials: "/testimonials",
  locations: "/locations",
  portal: "/login",
} as const
